# Generated by Django 4.1 on 2023-12-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpMaster',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('age', models.IntegerField()),
                ('deptno', models.IntegerField()),
            ],
        ),
    ]
